language: node_js
node_js:
  - '4'
script:
  - npm run test
  - npm run coveralls
after_success:
  - ./bin/build-gh-pages-travis
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: singpath/classmentors
    tags: true
  file: dist/classmentors.zip
  api_key:
    secure: Y+v6u5c1ETTuCWhwKSq+iQWb+zvyG5ALP+LQ9Dsvmu33WdTzEA2XrqPESn+C63Ubnt4HKt3bISW6QIn8I6uXS1KAyQpeXkWgJ+W5ZAf4DL/QQkYF9VZSSr7VKZJDRZB5CkzdxnEkjZOPo4OVS4IMS6nmg1tfl4yaJY7GSsI4hTyEcxiTundVWOY9dk8KTstjjKmz1yPQARhXY4tgarA/1DR/SDHNdOLU0WSk8aSbgel1BnHUXctfaHDh+ln3f5h8in2TaZixjiBkkSk8/lPRO98sEXGKZnIFIS/PJD6zSf3+2Cp5+Zd8iOD6E/G7StJ5lIpquTZnB0neHA94a83db6UpkY7ETUdrmzORCYiJ/k/CsQfBd8Hw4KPI96O5ZB3Frw81XP9GexsBxjBLeXrnM7tyBiAgSC/RGcrVOHX2pT7LdbpSlD+K/vbSNsH+Q6J0N6XNtchbETd1DpTPURSpms8zVZpBH33vWXoZ1wSI815QYcPtgPrUMAKK8JnuybeBwEh3yY1vQKEa/OWJwvcZ+vqwyVe3CzZO1GdseNYshB5P83h3UxmCNUbxl997kF946MiLBZ1WVoqHlT2O1MfDxfovqkR1fpwgTmONk0S2l3kc8A0TSCUX2NfNlwmfXtmBfhj3JBaI+S8oqflP4W3GNAyxUUgjFLkdIhEIgcwvpHY=
